import bcrypt from 'bcryptjs';

export const DEMO_USERS = [
  {
    _id: 'usr_superadmin',
    name: 'Super Administrator',
    email: 'admin.exhibition.com',
    passwordHash: bcrypt.hashSync('exhibition@123', 10),
    role: 'SUPER_ADMIN' as const,
    status: 'ACTIVE' as const,
    phone: '+1 (555) 019-2831',
    institution: 'Central Exhibition Committee',
    isActive: true,
  },
  {
    _id: 'usr_eventadmin',
    name: 'Prof. David Reynolds',
    email: 'eventadmin@portal.edu',
    passwordHash: bcrypt.hashSync('event123', 10),
    role: 'EVENT_ADMIN' as const,
    status: 'ACTIVE' as const,
    phone: '+1 (555) 018-9942',
    institution: 'Faculty of Science & Technology',
    isActive: true,
  },
  {
    _id: 'usr_evaluator_1',
    name: 'Dr. Elena Rostova',
    email: 'elena@evaluator.edu',
    passwordHash: bcrypt.hashSync('eval123', 10),
    role: 'EVALUATOR' as const,
    status: 'ACTIVE' as const,
    phone: '+1 (555) 012-4491',
    institution: 'Dept. of Electrical & Computer Eng.',
    isActive: true,
  },
  {
    _id: 'usr_evaluator_2',
    name: 'Prof. Marcus Vance',
    email: 'marcus@evaluator.edu',
    passwordHash: bcrypt.hashSync('eval123', 10),
    role: 'EVALUATOR' as const,
    status: 'ACTIVE' as const,
    phone: '+1 (555) 014-7721',
    institution: 'Robotics & Automation Institute',
    isActive: true,
  },
  {
    _id: 'usr_evaluator_3',
    name: 'Dr. Priya Sharma',
    email: 'priya@evaluator.edu',
    passwordHash: bcrypt.hashSync('eval123', 10),
    role: 'EVALUATOR' as const,
    status: 'ACTIVE' as const,
    phone: '+1 (555) 017-3312',
    institution: 'School of Environmental Science',
    isActive: true,
  },
  {
    _id: 'usr_student_1',
    name: 'Alex Chen',
    email: 'alex@student.edu',
    passwordHash: bcrypt.hashSync('student123', 10),
    role: 'STUDENT' as const,
    status: 'ACTIVE' as const,
    phone: '+1 (555) 011-8833',
    institution: 'Tech Valley High / College',
    isActive: true,
  },
  {
    _id: 'usr_student_2',
    name: 'Sophia Williams',
    email: 'sophia@student.edu',
    passwordHash: bcrypt.hashSync('student123', 10),
    role: 'STUDENT' as const,
    status: 'ACTIVE' as const,
    phone: '+1 (555) 015-6677',
    institution: 'Metro Polytechnic',
    isActive: true,
  },
  {
    _id: 'usr_student_3',
    name: 'Liam Patel',
    email: 'liam@student.edu',
    passwordHash: bcrypt.hashSync('student123', 10),
    role: 'STUDENT' as const,
    status: 'ACTIVE' as const,
    phone: '+1 (555) 016-1122',
    institution: 'St. Jude Academy of Arts',
    isActive: true,
  },
];

export const DEMO_EVENTS = [
  {
    _id: 'evt_science_2026',
    title: 'National Science & Innovation Exhibition 2026',
    slug: 'science-innovation-2026',
    description: 'Premier national exhibition showcasing student breakthroughs in renewable energy, healthcare robotics, AI automation, and sustainable green technology.',
    eventType: 'Science Exhibition',
    status: 'EVALUATION_RUNNING' as const,
    venue: 'Hall A & B, Innovation Pavilion',
    startDate: '2026-10-15',
    endDate: '2026-10-18',
    maxTeamSize: 4,
    minTeamSize: 1,
    bannerUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&w=1200&q=80',
    rules: '1. All hardware models must be safe and properly enclosed. 2. Projects must be present at their assigned stalls 15 mins prior to evaluator rounds. 3. Maximum presentation time is 7 minutes followed by 3 minutes Q&A.',
    allowPublicFeedback: true,
    createdBy: 'usr_superadmin',
  },
  {
    _id: 'evt_robotics_2026',
    title: 'Inter-College Autonomous Robotics Championship',
    slug: 'robotics-championship-2026',
    description: 'Competitive showcase featuring autonomous terrain-traversal rovers, warehouse cobots, and line-following high-precision bots.',
    eventType: 'Robotics Competition',
    status: 'REGISTRATION_OPEN' as const,
    venue: 'Arena 3, Engineering Complex',
    startDate: '2026-11-05',
    endDate: '2026-11-07',
    maxTeamSize: 5,
    minTeamSize: 2,
    bannerUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=80',
    rules: 'Bots must strictly adhere to the weight (< 8kg) and dimensions (40x40x40cm) guidelines. Remote kill switches are mandatory.',
    allowPublicFeedback: true,
    createdBy: 'usr_eventadmin',
  },
  {
    _id: 'evt_cultural_2026',
    title: 'Annual Inter-School Cultural & Performing Arts Fest',
    slug: 'cultural-arts-fest-2026',
    description: 'Celebration of traditional dance, instrumental acoustics, vocal harmony, and digital theatrical arts.',
    eventType: 'Cultural Competition',
    status: 'DRAFT' as const,
    venue: 'Grand Auditorium & Amphitheater',
    startDate: '2026-12-01',
    endDate: '2026-12-03',
    maxTeamSize: 12,
    minTeamSize: 1,
    bannerUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    rules: 'Time limit: 6 minutes performance + 2 minutes setup. Audio tracks must be submitted 24 hours prior.',
    allowPublicFeedback: true,
    createdBy: 'usr_eventadmin',
  },
];

export const DEMO_CATEGORIES = [
  {
    _id: 'cat_sci_01',
    eventId: 'evt_science_2026',
    name: 'AI & Sustainable Tech',
    code: 'AI-SUSTAIN',
    description: 'Artificial intelligence applications addressing ecology, energy reduction, and conservation.',
    maxTeams: 20,
  },
  {
    _id: 'cat_sci_02',
    eventId: 'evt_science_2026',
    name: 'Healthcare & Biomedical Devices',
    code: 'HEALTH-BIO',
    description: 'Affordable diagnostic tools, assistive prosthetics, and smart monitoring.',
    maxTeams: 15,
  },
  {
    _id: 'cat_sci_03',
    eventId: 'evt_science_2026',
    name: 'Applied Physics & Renewable Energy',
    code: 'PHYS-ENERGY',
    description: 'Solar efficiency innovations, kinetic harvesting, and micro-hydro prototypes.',
    maxTeams: 20,
  },
  {
    _id: 'cat_rob_01',
    eventId: 'evt_robotics_2026',
    name: 'Autonomous Maze Solvers',
    code: 'ROB-MAZE',
    description: 'Micromouse and LiDAR-guided autonomous labyrinth traversal.',
    maxTeams: 25,
  },
];

export const DEMO_CRITERIA = [
  {
    _id: 'crit_sci_01',
    eventId: 'evt_science_2026',
    name: 'Innovation & Originality',
    description: 'Novelty of the solution, creativity of approach, and distinction from existing market solutions.',
    maxMarks: 25,
    minMarks: 0,
    weight: 1,
    order: 1,
    isRequired: true,
  },
  {
    _id: 'crit_sci_02',
    eventId: 'evt_science_2026',
    name: 'Scientific Principle & Technical Depth',
    description: 'Soundness of theoretical foundation, data accuracy, and robust engineering architecture.',
    maxMarks: 25,
    minMarks: 0,
    weight: 1,
    order: 2,
    isRequired: true,
  },
  {
    _id: 'crit_sci_03',
    eventId: 'evt_science_2026',
    name: 'Working Prototype & Execution',
    description: 'Functionality of working model, reliability during live demonstration, and finish quality.',
    maxMarks: 30,
    minMarks: 0,
    weight: 1,
    order: 3,
    isRequired: true,
  },
  {
    _id: 'crit_sci_04',
    eventId: 'evt_science_2026',
    name: 'Presentation & Defense',
    description: 'Clarity of verbal explanation, answering evaluator questions, and team collaboration.',
    maxMarks: 20,
    minMarks: 0,
    weight: 1,
    order: 4,
    isRequired: true,
  },
];

export const DEMO_TEAMS = [
  {
    _id: 'team_01',
    eventId: 'evt_science_2026',
    categoryId: 'cat_sci_01',
    teamCode: 'SCI-0101',
    title: 'AeroPurify: Drone-Based Forest Canopy Air Quality Sensor Array',
    abstract: 'An autonomous low-altitude drone fitted with gas chromatographs and particulate sensors designed to map microclimates and industrial emissions in real time with edge ML.',
    techStack: 'Raspberry Pi 4, BME688 sensors, PyTorch Edge, LoRaWAN mesh transmitter',
    tableNumber: 'Stall A-01',
    teamLeaderId: 'usr_student_1',
    members: [
      { name: 'Alex Chen', email: 'alex@student.edu', rollNo: 'CS-2023-41', gradeOrDept: 'Computer Science', role: 'Team Lead' },
      { name: 'Chloe Vance', email: 'chloe@student.edu', rollNo: 'EE-2023-12', gradeOrDept: 'Electrical Eng', role: 'Hardware Architect' },
      { name: 'Rohan Gupta', email: 'rohan@student.edu', rollNo: 'EN-2023-88', gradeOrDept: 'Environmental Sc', role: 'Data Analyst' },
    ],
    projectLinks: [
      { title: 'GitHub Repository', url: 'https://github.com/demo/aeropurify' },
      { title: 'Live Dashboard Demo', url: 'https://aeropurify-demo.netlify.app' },
    ],
    mediaUrls: [
      'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'APPROVED' as const,
    correctionRemarks: '',
    qrCodeData: 'https://portal.edu/stall/SCI-0101',
  },
  {
    _id: 'team_02',
    eventId: 'evt_science_2026',
    categoryId: 'cat_sci_02',
    teamCode: 'SCI-0204',
    title: 'NeuroGlove: Low-Cost EMG Haptic Rehabilitation Glove',
    abstract: 'A 3D-printed rehabilitative glove utilizing surface electromyography (sEMG) signals to assist post-stroke patients in regaining fine motor finger dexterity via servo resistance.',
    techStack: 'ESP32, MyoWare Muscle Sensor 2.0, MG996R Servos, TensorFlow Lite',
    tableNumber: 'Stall A-02',
    teamLeaderId: 'usr_student_2',
    members: [
      { name: 'Sophia Williams', email: 'sophia@student.edu', rollNo: 'BM-2024-03', gradeOrDept: 'Biomedical Eng', role: 'Lead Researcher' },
      { name: 'Ethan Hunt', email: 'ethan@student.edu', rollNo: 'ME-2024-19', gradeOrDept: 'Mechanical Eng', role: 'CAD / 3D Printing' },
    ],
    projectLinks: [
      { title: 'Project Demo Video', url: 'https://youtube.com/watch?v=demo-neuroglove' },
    ],
    mediaUrls: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'APPROVED' as const,
    correctionRemarks: '',
    qrCodeData: 'https://portal.edu/stall/SCI-0204',
  },
  {
    _id: 'team_03',
    eventId: 'evt_science_2026',
    categoryId: 'cat_sci_03',
    teamCode: 'SCI-0309',
    title: 'HelioTrack: Dual-Axis Solar Photovoltaic Concentrator',
    abstract: 'High-efficiency Fresnel lens solar concentrator paired with an astronomical algorithm tracking mount to enhance energy yield by 34% over stationary panels.',
    techStack: 'Arduino Mega, LDR array, NEMA 17 Steppers, Monocrystalline Cells',
    tableNumber: 'Stall B-01',
    teamLeaderId: 'usr_student_3',
    members: [
      { name: 'Liam Patel', email: 'liam@student.edu', rollNo: 'PH-2023-77', gradeOrDept: 'Applied Physics', role: 'Lead Engineer' },
      { name: 'Nadia Thorne', email: 'nadia@student.edu', rollNo: 'EE-2023-99', gradeOrDept: 'Power Systems', role: 'Inverter Design' },
    ],
    projectLinks: [
      { title: 'Simulation Paper', url: 'https://arxiv.org/abs/demo-heliotrack' },
    ],
    mediaUrls: [
      'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'APPROVED' as const,
    correctionRemarks: '',
    qrCodeData: 'https://portal.edu/stall/SCI-0309',
  },
];

export const DEMO_ASSIGNMENTS = [
  // Evaluator 1 assigned to Team 1 and Team 2
  { _id: 'asg_01', eventId: 'evt_science_2026', evaluatorId: 'usr_evaluator_1', teamId: 'team_01', assignedAt: '2026-10-15T08:00:00Z' },
  { _id: 'asg_02', eventId: 'evt_science_2026', evaluatorId: 'usr_evaluator_1', teamId: 'team_02', assignedAt: '2026-10-15T08:00:00Z' },
  // Evaluator 2 assigned to Team 1 and Team 3
  { _id: 'asg_03', eventId: 'evt_science_2026', evaluatorId: 'usr_evaluator_2', teamId: 'team_01', assignedAt: '2026-10-15T08:00:00Z' },
  { _id: 'asg_04', eventId: 'evt_science_2026', evaluatorId: 'usr_evaluator_2', teamId: 'team_03', assignedAt: '2026-10-15T08:00:00Z' },
  // Evaluator 3 assigned to Team 2 and Team 3
  { _id: 'asg_05', eventId: 'evt_science_2026', evaluatorId: 'usr_evaluator_3', teamId: 'team_02', assignedAt: '2026-10-15T08:00:00Z' },
  { _id: 'asg_06', eventId: 'evt_science_2026', evaluatorId: 'usr_evaluator_3', teamId: 'team_03', assignedAt: '2026-10-15T08:00:00Z' },
];

export const DEMO_EVALUATIONS = [
  {
    _id: 'eval_01',
    eventId: 'evt_science_2026',
    teamId: 'team_01',
    evaluatorId: 'usr_evaluator_1',
    scores: [
      { criterionId: 'crit_sci_01', criterionName: 'Innovation & Originality', marks: 24, maxMarks: 25, comment: 'Exceptional application of edge ML on lightweight drone hardware.' },
      { criterionId: 'crit_sci_02', criterionName: 'Scientific Principle & Technical Depth', marks: 23, maxMarks: 25, comment: 'Calibration against reference sensors was scientifically sound.' },
      { criterionId: 'crit_sci_03', criterionName: 'Working Prototype & Execution', marks: 28, maxMarks: 30, comment: 'Flawless flight demonstration and telemetry downlink.' },
      { criterionId: 'crit_sci_04', criterionName: 'Presentation & Defense', marks: 19, maxMarks: 20, comment: 'Confident answers during cross-examination.' },
    ],
    totalScore: 94,
    maxPossibleScore: 100,
    generalFeedback: 'One of the strongest contenders this year. Outstanding engineering maturity.',
    isLocked: true,
    submittedAt: '2026-10-16T11:30:00Z',
    auditTrail: [
      { action: 'SUBMISSION', timestamp: '2026-10-16T11:30:00Z', ip: '192.168.1.104', userAgent: 'Mobile Safari / iOS 18' }
    ],
  },
  {
    _id: 'eval_02',
    eventId: 'evt_science_2026',
    teamId: 'team_02',
    evaluatorId: 'usr_evaluator_1',
    scores: [
      { criterionId: 'crit_sci_01', criterionName: 'Innovation & Originality', marks: 23, maxMarks: 25, comment: 'Great accessibility angle with 3D printing.' },
      { criterionId: 'crit_sci_02', criterionName: 'Scientific Principle & Technical Depth', marks: 22, maxMarks: 25, comment: 'Signal filtering can be improved for noisy environments.' },
      { criterionId: 'crit_sci_03', criterionName: 'Working Prototype & Execution', marks: 27, maxMarks: 30, comment: 'Smooth servo responsiveness to muscle contractions.' },
      { criterionId: 'crit_sci_04', criterionName: 'Presentation & Defense', marks: 18, maxMarks: 20, comment: 'Clear explanation of patient rehabilitation protocol.' },
    ],
    totalScore: 90,
    maxPossibleScore: 100,
    generalFeedback: 'High social and medical impact. Recommend testing with larger subject cohort.',
    isLocked: true,
    submittedAt: '2026-10-16T14:15:00Z',
    auditTrail: [
      { action: 'SUBMISSION', timestamp: '2026-10-16T14:15:00Z', ip: '192.168.1.104', userAgent: 'Mobile Safari / iOS 18' }
    ],
  },
];

export const DEMO_VISITOR_FEEDBACK = [
  {
    _id: 'fb_01',
    eventId: 'evt_science_2026',
    teamId: 'team_01',
    visitorName: 'Mark Henderson',
    visitorType: 'Parent / Industry Engineer',
    rating: 5,
    comments: 'Blown away by how responsive the drone sensor stream was on the live screen!',
    createdAt: '2026-10-16T12:00:00Z',
  },
  {
    _id: 'fb_02',
    eventId: 'evt_science_2026',
    teamId: 'team_02',
    visitorName: 'Jessica Taylor',
    visitorType: 'Medical Student',
    rating: 5,
    comments: 'I got to test the rehabilitation glove myself! The feedback loop feels very intuitive.',
    createdAt: '2026-10-16T14:30:00Z',
  },
];
